/* CheapFinder bookmarklet bundle — generated by tools/build-bookmarklet.mjs. Do not edit. */
(function(){
/* CheapFinder — product extraction.
 * Runs in a content script (isolated world) and inside the bookmarklet
 * (page world), so everything hangs off a single global namespace and
 * touches nothing else on the page. */
(function () {
  var CF = (globalThis.CheapFinder = globalThis.CheapFinder || {});

  var CURRENCY_SYMBOLS = {
    "$": "USD", "US$": "USD", "€": "EUR", "£": "GBP", "¥": "JPY",
    "C$": "CAD", "CA$": "CAD", "A$": "AUD", "AU$": "AUD", "₹": "INR",
    "kr": "SEK", "zł": "PLN", "R$": "BRL", "₩": "KRW", "CHF": "CHF"
  };
  var CURRENCY_CODES = /\b(USD|EUR|GBP|JPY|CAD|AUD|INR|SEK|NOK|DKK|PLN|BRL|KRW|CHF|CNY|MXN|NZD)\b/i;

  /* "1,299.99" / "1.299,99" / "1299" / "$ 12.50" -> { amount, currency, raw } */
  CF.parsePrice = function (raw) {
    if (raw == null) return null;
    if (typeof raw === "number") {
      return isFinite(raw) && raw > 0 ? { amount: raw, currency: null, raw: String(raw) } : null;
    }
    var s = String(raw).trim();
    if (!s) return null;

    var currency = null;
    var codeMatch = s.match(CURRENCY_CODES);
    if (codeMatch) currency = codeMatch[1].toUpperCase();
    if (!currency) {
      // Longest symbols first so "CA$" wins over "$".
      var symbols = Object.keys(CURRENCY_SYMBOLS).sort(function (a, b) { return b.length - a.length; });
      for (var i = 0; i < symbols.length; i++) {
        if (s.indexOf(symbols[i]) !== -1) { currency = CURRENCY_SYMBOLS[symbols[i]]; break; }
      }
    }

    var numMatch = s.replace(/\s/g, "").match(/\d[\d.,]*/);
    if (!numMatch) return null;
    var num = numMatch[0];

    var lastDot = num.lastIndexOf(".");
    var lastComma = num.lastIndexOf(",");
    var normalized;
    if (lastDot !== -1 && lastComma !== -1) {
      // Whichever separator comes last is the decimal separator.
      normalized = lastDot > lastComma
        ? num.replace(/,/g, "")
        : num.replace(/\./g, "").replace(",", ".");
    } else if (lastComma !== -1) {
      var afterComma = num.length - lastComma - 1;
      // Exactly one comma followed by 1-2 digits reads as a decimal
      // separator ("29,9", "29,90"); otherwise commas group thousands.
      normalized = (num.indexOf(",") === lastComma && afterComma > 0 && afterComma <= 2)
        ? num.replace(",", ".")
        : num.replace(/,/g, "");
    } else if (lastDot !== -1) {
      var afterDot = num.length - lastDot - 1;
      if (afterDot === 3) {
        // "1.299" / "1.234.567": dot-groups of three read as European
        // thousands separators, not $1.299.
        normalized = num.replace(/\./g, "");
      } else if (num.indexOf(".") !== lastDot) {
        // Multiple dots, short last group ("1.234.56"): all but the last
        // are thousands separators.
        normalized = num.slice(0, lastDot).replace(/\./g, "") + num.slice(lastDot);
      } else {
        normalized = num;
      }
    } else {
      normalized = num;
    }

    var amount = parseFloat(normalized);
    if (!isFinite(amount) || amount <= 0) return null;
    return { amount: amount, currency: currency, raw: s };
  };

  function firstString(v) {
    if (v == null) return null;
    if (typeof v === "string") return v.trim() || null;
    if (Array.isArray(v)) {
      for (var i = 0; i < v.length; i++) {
        var s = firstString(v[i]);
        if (s) return s;
      }
      return null;
    }
    if (typeof v === "object") return firstString(v.url || v.contentUrl || v.name || v["@id"]);
    return null;
  }

  function typeMatches(node, wanted) {
    var t = node && node["@type"];
    if (!t) return false;
    var types = Array.isArray(t) ? t : [t];
    return types.some(function (x) {
      return typeof x === "string" && x.toLowerCase().indexOf(wanted) !== -1;
    });
  }

  function collectJsonLdNodes(doc) {
    var out = [];
    var scripts = doc.querySelectorAll('script[type="application/ld+json"]');
    for (var i = 0; i < scripts.length; i++) {
      var parsed;
      try { parsed = JSON.parse(scripts[i].textContent); } catch (e) { continue; }
      var queue = Array.isArray(parsed) ? parsed.slice() : [parsed];
      while (queue.length) {
        var node = queue.shift();
        if (!node || typeof node !== "object") continue;
        out.push(node);
        if (Array.isArray(node["@graph"])) queue.push.apply(queue, node["@graph"]);
        if (node.mainEntity) queue.push(node.mainEntity);
      }
    }
    return out;
  }

  function offerPrice(offers) {
    if (!offers) return null;
    var list = Array.isArray(offers) ? offers : [offers];
    var best = null;
    for (var i = 0; i < list.length; i++) {
      var o = list[i];
      if (!o || typeof o !== "object") continue;
      var candidates = [o.price, o.lowPrice, o.highPrice];
      for (var j = 0; j < candidates.length; j++) {
        var p = CF.parsePrice(candidates[j]);
        if (p) {
          if (!p.currency && typeof o.priceCurrency === "string") p.currency = o.priceCurrency.toUpperCase();
          if (!best || p.amount < best.amount) best = p;
        }
      }
      if (Array.isArray(o.offers) || (o.offers && typeof o.offers === "object")) {
        var nested = offerPrice(o.offers);
        if (nested && (!best || nested.amount < best.amount)) best = nested;
      }
    }
    return best;
  }

  function fromJsonLd(doc) {
    var nodes = collectJsonLdNodes(doc);
    for (var i = 0; i < nodes.length; i++) {
      var node = nodes[i];
      if (!typeMatches(node, "product")) continue;
      var title = firstString(node.name);
      if (!title) continue;
      return {
        method: "json-ld",
        title: title,
        price: offerPrice(node.offers),
        image: firstString(node.image),
        brand: firstString(node.brand),
        sku: firstString(node.sku),
        gtin: firstString(node.gtin13 || node.gtin12 || node.gtin14 || node.gtin8 || node.gtin || node.mpn)
      };
    }
    return null;
  }

  function metaContent(doc, selector) {
    var el = doc.querySelector(selector);
    var c = el && el.getAttribute("content");
    return c ? c.trim() : null;
  }

  function fromOpenGraph(doc) {
    var ogType = metaContent(doc, 'meta[property="og:type"]') || "";
    var isProduct = ogType.toLowerCase().indexOf("product") !== -1;
    var priceAmount =
      metaContent(doc, 'meta[property="product:price:amount"]') ||
      metaContent(doc, 'meta[property="og:price:amount"]');
    // A bare meta[itemprop=price] also shows up on category/list pages, so
    // it only counts as a price source, never as the product trigger.
    if (!priceAmount && isProduct) priceAmount = metaContent(doc, 'meta[itemprop="price"]');
    if (!isProduct && !priceAmount) return null;

    var title = metaContent(doc, 'meta[property="og:title"]') || (doc.title || "").trim();
    if (!title) return null;
    var price = CF.parsePrice(priceAmount);
    if (price && !price.currency) {
      var cur =
        metaContent(doc, 'meta[property="product:price:currency"]') ||
        metaContent(doc, 'meta[property="og:price:currency"]') ||
        metaContent(doc, 'meta[itemprop="priceCurrency"]');
      if (cur) price.currency = cur.toUpperCase();
    }
    return {
      method: "opengraph",
      title: title,
      price: price,
      image: metaContent(doc, 'meta[property="og:image"]') || metaContent(doc, 'meta[property="og:image:url"]'),
      brand: metaContent(doc, 'meta[property="product:brand"]'),
      sku: metaContent(doc, 'meta[property="product:retailer_item_id"]'),
      gtin: null
    };
  }

  function itempropValue(scope, name) {
    var el = scope.querySelector('[itemprop="' + name + '"]');
    if (!el) return null;
    var v = el.getAttribute("content") || el.getAttribute("src") || el.getAttribute("href") || el.textContent;
    return v ? String(v).trim() || null : null;
  }

  function fromMicrodata(doc) {
    var scope = doc.querySelector('[itemtype*="schema.org/Product" i]');
    if (!scope) return null;
    var title = itempropValue(scope, "name");
    if (!title) return null;
    var price = CF.parsePrice(itempropValue(scope, "price") || itempropValue(scope, "lowPrice"));
    if (price && !price.currency) {
      var cur = itempropValue(scope, "priceCurrency");
      if (cur) price.currency = cur.toUpperCase();
    }
    return {
      method: "microdata",
      title: title,
      price: price,
      image: itempropValue(scope, "image"),
      brand: itempropValue(scope, "brand"),
      sku: itempropValue(scope, "sku"),
      gtin: itempropValue(scope, "gtin13") || itempropValue(scope, "gtin")
    };
  }

  var PRODUCT_PATH = /\/(products?|item|itm|dp|listing|p|pd|goods|prod)\/|-p-\d|\/p\d{5,}/i;

  var PRICE_PATTERN = /(?:US?\$|CA?\$|AU?\$|[$€£¥]|\b(?:USD|CAD|EUR|GBP|AUD)\b)\s?\d[\d.,]*/;

  // Shops almost universally label the price element with a "price" class.
  function guessPrice(doc) {
    var els = doc.querySelectorAll('[itemprop="price"], [data-price], [class*="price" i]');
    for (var i = 0; i < Math.min(els.length, 20); i++) {
      var t = (els[i].getAttribute("content") || els[i].textContent || "").slice(0, 60);
      var m = t.match(PRICE_PATTERN);
      var p = m && CF.parsePrice(m[0]);
      if (p) return p;
    }
    var body = doc.body ? (doc.body.textContent || "").slice(0, 200000) : "";
    var bm = body.match(PRICE_PATTERN);
    return bm ? CF.parsePrice(bm[0]) : null;
  }

  function guessImage(doc) {
    var og = metaContent(doc, 'meta[property="og:image"]');
    if (og) return og;
    var best = null, bestArea = 40000; // ignore icons/thumbnails
    var imgs = doc.images || [];
    for (var i = 0; i < Math.min(imgs.length, 300); i++) {
      var im = imgs[i];
      var src = im.currentSrc || im.src || "";
      if (!src || src.slice(0, 5) === "data:" || /\.svg(\?|$)/i.test(src)) continue;
      var area = (im.naturalWidth || im.width || 0) * (im.naturalHeight || im.height || 0);
      if (area > bestArea) { bestArea = area; best = src; }
    }
    return best;
  }

  // "SHEIN Frenchy Linen Pants | SHEIN USA" -> longest segment wins.
  function cleanTitle(t) {
    if (!t) return null;
    var parts = String(t).split(/\s*[|•]\s*/);
    var best = "";
    for (var i = 0; i < parts.length; i++) if (parts[i].length > best.length) best = parts[i];
    best = best.replace(/\s+/g, " ").trim();
    return best.length >= 3 ? best : null;
  }

  function bestGuessTitle(doc) {
    var h1 = doc.querySelector("h1");
    var t = h1 && h1.textContent ? cleanTitle(h1.textContent) : null;
    return t ||
      cleanTitle(metaContent(doc, 'meta[property="og:title"]')) ||
      cleanTitle(metaContent(doc, 'meta[name="twitter:title"]')) ||
      cleanTitle(doc.title);
  }

  function fromHeuristics(doc, loc) {
    if (!loc || !PRODUCT_PATH.test(loc.pathname || "")) return null;
    var title = bestGuessTitle(doc);
    if (!title) return null;
    return {
      method: "heuristic",
      title: title,
      price: guessPrice(doc),
      image: guessImage(doc),
      brand: null, sku: null, gtin: null
    };
  }

  function absolutize(url, loc) {
    if (!url) return null;
    try { return new URL(url, loc && loc.href ? loc.href : undefined).href; } catch (e) { return url; }
  }

  function finalize(p, loc) {
    p.found = true;
    p.title = p.title.replace(/\s+/g, " ").trim().slice(0, 300);
    p.image = absolutize(p.image, loc);
    p.url = loc && loc.href ? loc.href : null;
    return p;
  }

  CF.extractProduct = function (doc, loc) {
    var p = null;
    try { p = fromJsonLd(doc); } catch (e) {}
    if (!p) { try { p = fromOpenGraph(doc); } catch (e) {} }
    if (!p) { try { p = fromMicrodata(doc); } catch (e) {} }
    if (!p) { try { p = fromHeuristics(doc, loc); } catch (e) {} }
    if (!p) return { found: false };
    return finalize(p, loc);
  };

  /* For explicit invocations (the bookmarklet): the user asked, so always
   * produce a best guess rather than giving up — any title will do, with a
   * "fallback" method so the UI can flag lower confidence. */
  CF.extractProductLoose = function (doc, loc) {
    var p = CF.extractProduct(doc, loc);
    if (p.found) return p;
    var title = null;
    try { title = bestGuessTitle(doc); } catch (e) {}
    if (!title) return { found: false };
    var guess = { method: "fallback", title: title, brand: null, sku: null, gtin: null, price: null, image: null };
    try { guess.price = guessPrice(doc); } catch (e) {}
    try { guess.image = guessImage(doc); } catch (e) {}
    return finalize(guess, loc);
  };
})();

/* CheapFinder — drop-shipping signal scoring.
 * Every check is a heuristic; the panel presents them as signals, never
 * as proof. Scores are additive and capped at MAX_SCORE. Signals are
 * deliberately conservative: apps like Loox/AfterShip that plenty of
 * legitimate shops use do NOT count. */
(function () {
  var CF = (globalThis.CheapFinder = globalThis.CheapFinder || {});

  CF.MAX_SCORE = 10;

  // Apps whose sole purpose is drop-ship fulfilment / AliExpress import.
  var DROPSHIP_APPS = [
    "dsers", "oberlo", "zendrop", "cjdropshipping", "spocket", "autods",
    "eprolo", "dropified", "importify", "alireviews"
  ];

  function scriptSources(doc) {
    var out = [];
    var scripts = doc.querySelectorAll("script[src]");
    for (var i = 0; i < scripts.length; i++) out.push(scripts[i].getAttribute("src") || "");
    return out.join("\n").toLowerCase();
  }

  // Word-ish boundary match so "autods" can't fire inside a random hash.
  function containsToken(haystack, needle) {
    return new RegExp("(^|[^a-z0-9])" + needle + "([^a-z0-9]|$)").test(haystack);
  }

  function imageSources(doc) {
    var out = [];
    var imgs = doc.querySelectorAll("img[src], img[data-src], source[srcset]");
    for (var i = 0; i < imgs.length; i++) {
      out.push(imgs[i].getAttribute("src") || "", imgs[i].getAttribute("data-src") || "", imgs[i].getAttribute("srcset") || "");
    }
    return out.join("\n").toLowerCase();
  }

  /* Selector probes only — never serialize the document (huge DOMs). */
  function detectPlatform(doc, srcs) {
    if (srcs.indexOf("cdn.shopify.com") !== -1 ||
        doc.querySelector('link[href*="cdn.shopify.com"], meta[content*="Shopify" i]')) return "Shopify";
    var gen = doc.querySelector('meta[name="generator"]');
    var g = gen && gen.getAttribute("content") ? gen.getAttribute("content").toLowerCase() : "";
    if (g.indexOf("woocommerce") !== -1 ||
        doc.querySelector('link[href*="/wp-content/plugins/woocommerce"], body.woocommerce, body.woocommerce-page')) return "WooCommerce";
    if (g.indexOf("wix") !== -1) return "Wix";
    if (g.indexOf("bigcommerce") !== -1 || srcs.indexOf("bigcommerce.com") !== -1) return "BigCommerce";
    return null;
  }

  // Delivery ranges only count near shipping-related words, so "refunds are
  // processed in 7-14 days" in a returns policy doesn't fire.
  // The gap must not cross into returns/refund/warranty talk, so "free
  // shipping on all orders, returns accepted within 14-30 days" won't fire.
  var SHIPPING_RANGE = /(?:shipping|delivery|deliver(?:y|ed)?|arriv\w+|dispatch\w*|transit)(?:(?!return|refund|warrant)[^.!?]){0,80}?(\d{1,2})\s*(?:-|–|to)\s*(\d{1,2})\s*(?:business\s*|working\s*)?days/;

  /* domainAgeMonths comes from the background RDAP lookup and may be null. */
  CF.assessDropship = function (doc, opts) {
    opts = opts || {};
    var signals = [];
    var srcs = "";
    var imgs = "";
    var text = "";
    try { srcs = scriptSources(doc); } catch (e) {}
    try { imgs = imageSources(doc); } catch (e) {}
    try { text = (doc.body ? doc.body.textContent || "" : "").toLowerCase(); } catch (e) {}

    var platform = null;
    try { platform = detectPlatform(doc, srcs); } catch (e) {}
    if (platform === "Shopify" || platform === "WooCommerce" || platform === "Wix") {
      signals.push({ id: "platform", weight: 1, label: platform + " storefront (common for drop-ship shops)" });
    }

    var apps = DROPSHIP_APPS.filter(function (a) { return containsToken(srcs, a); });
    if (apps.length) {
      signals.push({ id: "apps", weight: 3, label: "Drop-shipping app detected: " + apps.slice(0, 3).join(", ") });
    }

    if (imgs.indexOf("alicdn.com") !== -1 || imgs.indexOf("aliexpress-media.com") !== -1 || imgs.indexOf("kwcdn.com") !== -1) {
      signals.push({ id: "cdn", weight: 3, label: "Product images hosted on AliExpress/Temu CDNs" });
    }

    var shipMatch = text.match(SHIPPING_RANGE);
    if (shipMatch && parseInt(shipMatch[2], 10) >= 10) {
      signals.push({ id: "shipping", weight: 2, label: "Long delivery estimate on page (" + shipMatch[1] + "-" + shipMatch[2] + " days)" });
    } else if (/ships?\s+from\s+(china|overseas)|overseas\s+warehouse/.test(text)) {
      signals.push({ id: "shipping", weight: 2, label: "Page mentions shipping from China / overseas warehouse" });
    }

    // "Only N left in stock" alone is genuine retail phrasing (Amazon uses
    // it) — only social-pressure widgets count.
    if (/people\s+are\s+viewing|selling\s+fast|hurry[,!\s]|sale\s+ends\s+in|\d+\s+sold\s+in\s+the\s+last/.test(text)) {
      signals.push({ id: "urgency", weight: 1, label: "Urgency widgets (social-pressure pattern)" });
    }

    if (/free\s+worldwide\s+shipping/.test(text)) {
      signals.push({ id: "worldwide", weight: 1, label: "“Free worldwide shipping” offer" });
    }

    if (typeof opts.domainAgeMonths === "number" && opts.domainAgeMonths >= 0 && opts.domainAgeMonths < 18) {
      signals.push({ id: "domain-age", weight: 2, label: "Domain registered only " + opts.domainAgeMonths + " month(s) ago" });
    }

    var score = 0;
    for (var i = 0; i < signals.length; i++) score += signals[i].weight;
    if (score > CF.MAX_SCORE) score = CF.MAX_SCORE;

    var verdict, tone;
    if (score >= 6) { verdict = "High chance this is drop-shipped"; tone = "bad"; }
    else if (score >= 3) { verdict = "Some drop-shipping signals"; tone = "warn"; }
    else { verdict = "Few drop-shipping signals"; tone = "ok"; }

    return { score: score, max: CF.MAX_SCORE, signals: signals, verdict: verdict, tone: tone, platform: platform };
  };
})();

/* CheapFinder — comparison-site definitions and query helpers. */
(function () {
  var CF = (globalThis.CheapFinder = globalThis.CheapFinder || {});

  var NOISE_WORDS = [
    "new", "hot", "sale", "best", "premium", "luxury", "official", "original",
    "free", "shipping", "2024", "2025", "2026", "upgraded", "improved", "pcs",
    "pack", "set", "with", "for", "and", "the", "a", "an", "of", "in", "on",
    "to", "by", "black", "white", "friday"
  ];

  CF.buildSearchQuery = function (product) {
    var title = (product && product.title) || "";
    var tokens = title
      .replace(/[|/,()\[\]{}™®©–—-]+/g, " ")
      .split(/\s+/)
      .map(function (t) {
        // Strip leading/trailing punctuation so "Shipping!" is recognized
        // as the noise word "shipping". \p{L}/\p{N} keep non-ASCII letters
        // (Japanese titles, accented brands) intact.
        return t.replace(/^[^\p{L}\p{N}]+|[^\p{L}\p{N}]+$/gu, "");
      })
      .filter(function (t) {
        return t && NOISE_WORDS.indexOf(t.toLowerCase()) === -1;
      });
    var q = tokens.slice(0, 8).join(" ").trim();
    if (product && product.brand) {
      // Token-boundary check so brand "LE" isn't "found" inside "LEather".
      var esc = product.brand.toLowerCase().replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      if (!new RegExp("(^|[^a-z0-9])" + esc + "([^a-z0-9]|$)").test(q.toLowerCase())) {
        q = product.brand + " " + q;
      }
    }
    return q.slice(0, 120).trim() || title.slice(0, 120).trim();
  };

  function enc(q) { return encodeURIComponent(q); }

  /* live:true means the extension background worker tries to fetch and
   * parse real prices; everything else is a one-tap search link. */
  CF.SITES = [
    { id: "amazon", name: "Amazon", live: true, host: "amazon.com",
      searchUrl: function (q) { return "https://www.amazon.com/s?k=" + enc(q); } },
    { id: "ebay", name: "eBay", live: true, host: "ebay.com",
      searchUrl: function (q) { return "https://www.ebay.com/sch/i.html?_nkw=" + enc(q); } },
    { id: "aliexpress", name: "AliExpress", live: false, host: "aliexpress.com",
      searchUrl: function (q) { return "https://www.aliexpress.com/wholesale?SearchText=" + enc(q); } },
    { id: "temu", name: "Temu", live: false, host: "temu.com",
      searchUrl: function (q) { return "https://www.temu.com/search_result.html?search_key=" + enc(q); } },
    { id: "walmart", name: "Walmart", live: false, host: "walmart.com",
      searchUrl: function (q) { return "https://www.walmart.com/search?q=" + enc(q); } },
    { id: "gshopping", name: "Google Shopping", live: false, host: "google.com",
      searchUrl: function (q) { return "https://www.google.com/search?udm=28&q=" + enc(q); } }
  ];

  CF.lensUrl = function (imageUrl) {
    if (!imageUrl || !/^https?:\/\//i.test(imageUrl)) return null;
    return "https://lens.google.com/uploadbyurl?url=" + encodeURIComponent(imageUrl);
  };

  var STOP = { the: 1, a: 1, an: 1, and: 1, or: 1, of: 1, for: 1, with: 1, to: 1, in: 1, on: 1, "new": 1 };

  function tokenSet(s) {
    var set = {};
    String(s || "").toLowerCase().replace(/[^a-z0-9 ]+/g, " ").split(/\s+/).forEach(function (t) {
      if (t.length > 1 && !STOP[t]) set[t] = 1;
    });
    return set;
  }

  /* Asymmetric query coverage: what fraction of the QUERY's tokens appear
   * in the candidate title. Deliberately not min-overlap: a short accessory
   * title like "iphone 15 case" must not score high against a query for
   * the phone itself, while a long Amazon essay-title that contains all
   * query tokens scores 1.0. Call as (query, candidateTitle). */
  CF.titleSimilarity = function (query, candidate) {
    var A = tokenSet(query), B = tokenSet(candidate);
    var keysA = Object.keys(A);
    if (!keysA.length || !Object.keys(B).length) return 0;
    var inter = 0;
    for (var i = 0; i < keysA.length; i++) if (B[keysA[i]]) inter++;
    return inter / keysA.length;
  };
})();

/* CheapFinder — popover UI. Rendered inside a shadow root so page CSS
 * can't restyle it. All dynamic strings (product titles, prices —
 * including ones parsed out of third-party search results) are set via
 * textContent, never innerHTML. */
(function () {
  var CF = (globalThis.CheapFinder = globalThis.CheapFinder || {});

  var STYLE = "" +
    ":host{all:initial}" +
    "*{box-sizing:border-box;margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif}" +
    ".root{position:fixed;bottom:16px;right:16px;z-index:2147483647;color:#e8eaed}" +
    ".badge{display:flex;align-items:center;gap:6px;background:#1a1c22;border:1px solid #34384a;border-radius:999px;" +
      "padding:8px 14px;font-size:13px;font-weight:600;cursor:pointer;box-shadow:0 4px 16px rgba(0,0,0,.35);color:#e8eaed}" +
    ".badge:hover{border-color:#5b8cff}" +
    ".badge .dot{width:8px;height:8px;border-radius:50%;background:#5b8cff}" +
    ".badge .dot.warn{background:#f0b429}.badge .dot.bad{background:#ef5350}.badge .dot.ok{background:#46c07a}" +
    ".panel{width:min(360px,calc(100vw - 32px));max-height:min(560px,calc(100vh - 32px));overflow-y:auto;background:#1a1c22;" +
      "border:1px solid #34384a;border-radius:14px;box-shadow:0 8px 32px rgba(0,0,0,.5);font-size:13px}" +
    ".hdr{display:flex;align-items:center;justify-content:space-between;padding:10px 14px;border-bottom:1px solid #2a2d38}" +
    ".hdr .brand{font-weight:700;font-size:13px;letter-spacing:.2px}" +
    ".hdr .brand span{color:#5b8cff}" +
    ".iconbtn{background:none;border:none;color:#9aa0a6;cursor:pointer;font-size:15px;padding:2px 6px;border-radius:6px}" +
    ".iconbtn:hover{background:#2a2d38;color:#e8eaed}" +
    ".prod{display:flex;gap:10px;padding:12px 14px;align-items:center}" +
    ".prod img{width:44px;height:44px;object-fit:cover;border-radius:8px;background:#2a2d38;flex:none}" +
    ".prod .t{font-weight:600;line-height:1.35;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}" +
    ".prod .p{color:#9aa0a6;margin-top:2px;font-size:12px}" +
    ".verdict{margin:0 14px 10px;padding:8px 10px;border-radius:9px;font-weight:600;font-size:12.5px;display:flex;justify-content:space-between;align-items:center;cursor:pointer}" +
    ".verdict.bad{background:rgba(239,83,80,.12);color:#ff8a80}" +
    ".verdict.warn{background:rgba(240,180,41,.12);color:#ffd54f}" +
    ".verdict.ok{background:rgba(70,192,122,.12);color:#69db97}" +
    ".verdict .chev{font-weight:400;opacity:.7}" +
    ".signals{margin:0 14px 10px;padding:0 2px;list-style:none;color:#b6bac2;font-size:12px;display:none}" +
    ".signals li{padding:3px 0 3px 16px;position:relative}" +
    ".signals li:before{content:'•';position:absolute;left:4px;color:#5b8cff}" +
    "table{width:100%;border-collapse:collapse}" +
    "th{text-align:left;color:#9aa0a6;font-size:11px;text-transform:uppercase;letter-spacing:.4px;padding:6px 14px;border-top:1px solid #2a2d38}" +
    "td{padding:7px 14px;border-top:1px solid #23252e;vertical-align:top}" +
    "td.site{font-weight:600;white-space:nowrap}" +
    "td.price{text-align:right;white-space:nowrap}" +
    ".best td{background:rgba(70,192,122,.08)}" +
    ".best td.price .amt{color:#69db97;font-weight:700}" +
    "a{color:#8ab4f8;text-decoration:none}a:hover{text-decoration:underline}" +
    ".muted{color:#9aa0a6}.small{font-size:11.5px}" +
    ".match{display:block;color:#9aa0a6;font-size:11px;max-width:190px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}" +
    ".spin{display:inline-block;width:11px;height:11px;border:2px solid #34384a;border-top-color:#8ab4f8;border-radius:50%;animation:cfspin .8s linear infinite;vertical-align:-2px}" +
    "@keyframes cfspin{to{transform:rotate(360deg)}}" +
    ".foot{padding:9px 14px 12px;color:#70757d;font-size:11px;line-height:1.45;border-top:1px solid #2a2d38}" +
    ".foot a{color:#9aa0a6}" +
    "@media (max-width:480px){.root{bottom:8px;right:8px;left:8px}.panel{width:auto}}";

  function el(tag, cls, text) {
    var e = document.createElement(tag);
    if (cls) e.className = cls;
    if (text != null) e.textContent = text;
    return e;
  }

  function link(href, text, cls) {
    var a = el("a", cls || null, text);
    a.href = href;
    a.target = "_blank";
    a.rel = "noopener noreferrer nofollow";
    return a;
  }

  function fmtPrice(p) {
    if (!p) return null;
    var cur = p.currency;
    var sym = cur === "USD" ? "$" : cur === "EUR" ? "€" : cur === "GBP" ? "£" : cur ? cur + " " : "$";
    return sym + (Math.round(p.amount * 100) / 100).toFixed(2);
  }

  /* opts: { product, assessment, sites, query, currentHost, liveEnabled, onClose } */
  CF.mountPanel = function (opts) {
    var host = el("div");
    host.setAttribute("data-cheapfinder", "1");
    // Closed by default so the (possibly hostile) shop page can't rewrite
    // the verdict or swap link targets. opts.exposeShadow is a test hook.
    var shadow = host.attachShadow({ mode: opts.exposeShadow ? "open" : "closed" });
    // adoptedStyleSheets is immune to the page's style-src CSP; fall back
    // to a <style> element where constructable sheets are unavailable.
    try {
      var sheet = new CSSStyleSheet();
      sheet.replaceSync(STYLE);
      shadow.adoptedStyleSheets = [sheet];
    } catch (e) {
      var style = el("style");
      style.textContent = STYLE;
      shadow.appendChild(style);
    }

    var root = el("div", "root");
    shadow.appendChild(root);

    var state = { open: false, rows: {} };
    var tone = (opts.assessment && opts.assessment.tone) || "ok";

    var badge = el("button", "badge");
    badge.appendChild(el("span", "dot " + tone));
    badge.appendChild(el("span", null, "CheapFinder"));

    var panel = el("div", "panel");

    var hdr = el("div", "hdr");
    var brand = el("div", "brand", "Cheap");
    brand.appendChild(el("span", null, "Finder"));
    hdr.appendChild(brand);
    var closeBtn = el("button", "iconbtn", "✕");
    closeBtn.setAttribute("aria-label", "Collapse");
    hdr.appendChild(closeBtn);
    panel.appendChild(hdr);

    var prod = el("div", "prod");
    if (opts.product.image) {
      var img = el("img");
      img.src = opts.product.image;
      img.alt = "";
      img.addEventListener("error", function () { img.remove(); });
      prod.appendChild(img);
    }
    var pText = el("div");
    pText.appendChild(el("div", "t", opts.product.title));
    var pagePrice = fmtPrice(opts.product.price);
    var sub = pagePrice ? "This page: " + pagePrice : "Price on page not detected";
    if (opts.product.method === "fallback") sub += " · best guess, check the title";
    pText.appendChild(el("div", "p", sub));
    prod.appendChild(pText);
    panel.appendChild(prod);

    if (opts.assessment) {
      var verdict = el("div", "verdict " + tone);
      verdict.appendChild(el("span", null,
        opts.assessment.verdict + " (" + opts.assessment.score + "/" + opts.assessment.max + ")"));
      verdict.appendChild(el("span", "chev", "▾"));
      panel.appendChild(verdict);
      var sigList = el("ul", "signals");
      if (opts.assessment.signals.length) {
        opts.assessment.signals.forEach(function (s) {
          sigList.appendChild(el("li", null, s.label + " (+" + s.weight + ")"));
        });
      } else {
        sigList.appendChild(el("li", null, "No drop-shipping markers found on this page"));
      }
      panel.appendChild(sigList);
      verdict.addEventListener("click", function () {
        sigList.style.display = sigList.style.display === "block" ? "none" : "block";
      });
    }

    var table = el("table");
    var thead = el("thead");
    var thr = el("tr");
    thr.appendChild(el("th", null, "Site"));
    var thPrice = el("th", null, "Best price");
    thPrice.style.textAlign = "right";
    thr.appendChild(thPrice);
    thead.appendChild(thr);
    table.appendChild(thead);
    var tbody = el("tbody");
    table.appendChild(tbody);

    (opts.sites || []).forEach(function (site) {
      var h = opts.currentHost || "";
      if (h === site.host || h.slice(-(site.host.length + 1)) === "." + site.host) return;
      var tr = el("tr");
      var tdSite = el("td", "site");
      tdSite.appendChild(link(site.searchUrl(opts.query), site.name));
      tr.appendChild(tdSite);
      var tdPrice = el("td", "price");
      if (site.live && opts.liveEnabled) {
        tdPrice.appendChild(el("span", "spin"));
      } else {
        tdPrice.appendChild(link(site.searchUrl(opts.query), "search →", "small"));
      }
      tr.appendChild(tdPrice);
      tbody.appendChild(tr);
      state.rows[site.id] = { tr: tr, tdPrice: tdPrice, site: site };
    });

    var lens = CF.lensUrl(opts.product.image);
    if (lens) {
      var tr = el("tr");
      var tdSite = el("td", "site");
      tdSite.appendChild(link(lens, "Google Lens"));
      tr.appendChild(tdSite);
      var tdPrice = el("td", "price");
      tdPrice.appendChild(link(lens, "by image →", "small"));
      tr.appendChild(tdPrice);
      tbody.appendChild(tr);
    }
    panel.appendChild(table);

    var foot = el("div", "foot");
    foot.appendChild(document.createTextNode(
      "Heuristics only — verify before buying. No tracking or accounts; " +
      (opts.liveEnabled
        ? "live lookups query Amazon/eBay directly (toggle in settings). "
        : "links only, nothing leaves this page. ")));
    foot.appendChild(link("https://github.com/tooaverage/cheapfinder", "About"));
    panel.appendChild(foot);

    function setOpen(open) {
      state.open = open;
      root.textContent = "";
      root.appendChild(open ? panel : badge);
    }
    badge.addEventListener("click", function () { setOpen(true); });
    closeBtn.addEventListener("click", function () {
      setOpen(false);
      if (opts.onClose) opts.onClose();
    });

    setOpen(!!opts.startOpen);
    (document.body || document.documentElement).appendChild(host);

    return {
      host: host,
      /* result: {status:'done'|'error', results:[{title,priceRaw,priceAmount,url}]} */
      setLive: function (siteId, result) {
        var row = state.rows[siteId];
        if (!row) return;
        var td = row.tdPrice;
        td.textContent = "";
        var results = (result && result.results) || [];
        if (result && result.status === "done" && results.length) {
          var best = results[0];
          var a = link(best.url || row.site.searchUrl(opts.query), best.priceRaw || "view");
          a.className = "amt";
          td.appendChild(a);
          if (best.title) {
            var m = el("span", "match", best.title);
            m.title = best.title;
            td.appendChild(m);
          }
        } else {
          td.appendChild(link(row.site.searchUrl(opts.query), "search →", "small muted"));
        }
      },
      isOpen: function () { return state.open; },
      markBest: function (siteId) {
        var row = state.rows[siteId];
        if (row) row.tr.className = "best";
      },
      destroy: function () { host.remove(); }
    };
  };
})();

/* CheapFinder — bookmarklet entry point. The build script concatenates the
 * shared modules above this file and wraps everything in an IIFE, so CF is
 * fully populated by the time this runs. Runs in the page's world: no
 * chrome.* APIs, no cross-origin fetch — links-only mode. */
(function () {
  var CF = globalThis.CheapFinder;

  // Second tap on the bookmark removes the panel.
  var existing = document.querySelector("[data-cheapfinder]");
  if (existing) { existing.remove(); return; }

  // Loose extraction: the user tapped the bookmark on purpose, so always
  // show the panel with a best guess instead of giving up (heavy SPAs like
  // Shein expose no structured product data).
  var product = CF.extractProductLoose(document, location);
  if (!product.found) {
    alert("CheapFinder: couldn't find anything that looks like a product here.");
    return;
  }

  var assessment = CF.assessDropship(document, {});
  var query = CF.buildSearchQuery(product);

  CF.mountPanel({
    product: product,
    assessment: assessment,
    sites: CF.SITES,
    query: query,
    currentHost: location.hostname,
    liveEnabled: false,
    exposeShadow: !!globalThis.__CF_TEST_OPEN_SHADOW, // test hook
    startOpen: true
  });
})();

})();
